version: "3.1"

services:

  db:
    container_name: prestashop-mysql
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
      MYSQL_ROOT_PASSWORD: javier
    volumes:
      - /home/javier/Docker/Volumes/tarea4/db:/var/lib/mysql

  mediawiki:
    container_name: prestashop
    image: javierpzh/prestashop:v1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /home/javier/Docker/Volumes/tarea4/app:/var/www/html
